// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Speakeasy-API/pkg/models/shared"
	"net/http"
)

type GetAllForVersionAPIEndpointsRequest struct {
	// The ID of the Api to retrieve ApiEndpoints for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to retrieve ApiEndpoints for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type GetAllForVersionAPIEndpointsResponse struct {
	// OK
	APIEndpoints []shared.APIEndpoint
	ContentType  string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
