// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Speakeasy-API/pkg/models/shared"
	"net/http"
)

type UpsertPluginResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	Plugin      *shared.Plugin
	StatusCode  int
	RawResponse *http.Response
}
